version: '3.3'

services:
    db:
#        restart: always
        image: mysql/mysql-server:5.7.28
        container_name: mlflow_db
        expose:
            - "3306"
        networks:
            - backend
        env_file:
          - local.env
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        volumes:
            - /tmp/mysql:/var/lib/mysql

    web:
#        restart: always
#        build: ./mlflow_db
        image: larribas/mlflow
        container_name: mlflow_server
        expose:
            - "5000"
        networks:
#            - frontend
            - backend
        external_links:
            - db
        env_file:
          - local.env
        environment:
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
            - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
        volumes:
            - ./artifact-root:/artifact-root
        command: --default-artifact-root /artifact-root --backend-store-uri mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE} --host 0.0.0.0
        # --default-artifact-root s3://mlflow_bucket/mlflow/

#    nginx:
#        restart: always
#        build: ./nginx
#        image: mlflow_nginx
#        container_name: mlflow_nginx
#        ports:
#            - "80:80"
#        networks:
#            - frontend
#        depends_on:
#            - web

networks:
#    frontend:
#        driver: bridge
    backend:
        driver: bridge

volumes:
    dbdata: